### ISSUE TITLE
Onclick action for logout cannot work in normal cases

### ISSUE THREAD

**Issue by RAD-X** [josebalius/jquery-idleTimeout#5]
If I use $.fn.idleTimeout().logout(); in logout link, then href action is faster than script. So the user isn't never logged off and logout page keeps reloading.
In your example probably works only because you use "target="_blank" or something similar.
Suggested fix: Add a "return false;" or something similar into fn logoutUser.

**Comment by RAD-X** [comment]
BTW thanks for nice work! Nice script, well documented, iframe support, ... best jquery iddle time logout that I've seen.

**Comment by JillElaine** [comment]
This issue was filed under josebalius/jquery-idleTimeout, which does not have the $.fn.idleTimeout().logout() or other features to which you refer. I think perhaps the issue was meant to be filed under https://github.com/JillElaine/jquery-idleTimeout ? Could you please close this issue and refile it under the right fork? Meanwhile, I will work on the issue. Thank you!

**Comment by RAD-X** [comment]
Sorry,
my mistake. :-)
