### ISSUE TITLE
Bootastrap modal window

### ISSUE THREAD

**Issue by hrvojegolcic** [josebalius/jquery-idleTimeout#6]
Is there an easy way to trigger a bootstrap modal window instead of default dialog window?

**Comment by josebalius** [comment]
@hrvojegolcic unfortunately, no it relies on jquery's modal, bootstrap would have to be added in.

**Comment by hrvojegolcic** [comment]
I guess I'd do that. Any specific point maybe I should be aware of?

**Comment by josebalius** [comment]
@hrvojegolcic not really, i think you would probably want to start here: https://github.com/josebalius/jquery-idleTimeout/blob/master/jquery-idleTimeout.js#L57 and re-implement that function to open a bootstrap dialog vs the jquery one.

**Comment by hrvojegolcic** [comment]
Great! Thanks! Let's do it...

**Comment by JillElaine** [comment]
You might look at this fork. It's quite a diversion from josebalius' idleTimeout though. https://github.com/Nigrimmist/jquery-idleTimeout

**Comment by josebalius** [comment]
@hrvojegolcic yeah, @JillElaine has also done some good work on her fork, and the one above is also good ^^^ so many options :)

**Comment by hrvojegolcic** [comment]
I need to do my homework first then :P

**Comment by JillElaine** [comment]
Lots of forks! This one specifically mentions bootstrap. https://github.com/OneSourceInformationServices/jquery-idleTimeout

**Comment by hrvojegolcic** [comment]
Thank you so much for all the info. I have tried https://github.com/OneSourceInformationServices/jquery-idleTimeout but it doesn't really work well for me. I gave up after encountering more and more bugs.

It works great with others:
https://github.com/josebalius/jquery-idleTimeout
https://github.com/Nigrimmist/jquery-idleTimeout
https://github.com/JillElaine/jquery-idleTimeout

I think for me it might be easier to adapt those. Now I'm thinking which one of the two is better to take to adapt for Bootstrap modals? What is the difference?

**Comment by JillElaine** [comment]
Nigrimmist's is a fork of JillElaine's (mine) most recent (version 1.0.10) IdleTimeout, but modified to "render own popup". I have not reviewed or tested this fork. My first code was a fork of josebalius' IdleTimeout (who first introduced the use of local storage variables to sync across multiple windows & tabs - hooray for that!). Josebalius merged my fork back into his at version 1.03. Since 1.03, I've added several requested features, including more configuration variables and iframe functionality. Please read the changelog: https://github.com/JillElaine/jquery-idleTimeout/blob/master/changelog for more details. Note that my script does have some open issues.

**Comment by hrvojegolcic** [comment]
Thank you so much for the clarification and the support. Indeed Nigrimmist's fork offers easy way to implement Bootstrap window via configuration options onPopupRequired and useCustomPopup. I have just done it, tested and works fine, without a need to modify the code. 

There are some issues indeed but it do the work very nice. Thank you all for the effort

Just out of couriosity I've found in Bower this one. Does it do the same thing?
https://github.com/LinearSoft/jquery-idleTimeout-plus

**Comment by JillElaine** [comment]
I have not tested or reviewed that fork. Best to read LinearSoft's changelog and README.
